Module2 task1
htmlacademy-react/1761315-six-cities-10 pull request #3
Opened 2022-07-10 18:45 UTC by grund1k

2022-07-11 05:07 UTC, PolyDevil requested changes

2022-07-11 05:07 UTC, PolyDevil commented on project/src/components/app/app.tsx
> +type AppProps = {
Просто  `Props` будет достаточно.
Типы используются в пределах одного файла все равно.
Даже если сделаем экспорт, то можно переименовывать при импорте, скажем
 ```
import App, { Props as AppProps } from './components/app/app';
 ```

2022-07-11 05:07 UTC, PolyDevil commented on project/src/components/app/app.tsx
> +function App({rentalOffersCount}: AppProps): JSX.Element {
В реакте предпочтительнее стрелочные функции, потому что они не имеют своего контекста.
 ```js
 // без явного return
 const App = ({ name }: Props) => (
   <div>{name}</div>
 )
 
 // с явным return:
 const App = ({ name }: Props) => {
   return (
     <div>{name}</div>
   )
 } 
 ```

2022-07-11 05:07 UTC, PolyDevil commented on project/src/pages/main/main.tsx
> +type MainpProps = {
У нас уже есть в коде этот тип, можно его импортировать.

2022-07-11 11:28 UTC, grund1k commented on project/src/components/app/app.tsx
> +function App({rentalOffersCount}: AppProps): JSX.Element {
Контекст может привести к каким-то багам? Мы ведь к нему не обращаемся. Или это просто договоренность?

2022-07-13 06:16 UTC, PolyDevil approved these changes

2022-07-13 06:16 UTC, merged